baseURL = "https://sentientchip.com"
disableLanguages = ["fr"]
disqusShortname = ""
googleAnalytics = ""
hasCJKLanguage = false
summaryLength = "10"
theme = "hydrogen-hugo"
timeZone = "GMT+2"
title = "Cybersecurity Trainings"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[imaging]
quality = 90
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "dracula"
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[module.hugoVersion]
extended = true
min = "0.90.1"
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "WebAppManifest"]
